export const SEARCHSONG_WAIT = "SEARCHSONG_WAIT";
export const SEARCHSONG_SUCCESS = "SEARCHSONG_SUCCESS";
export const SEARCHSONG_FAIL = "SEARCHSONG_FAIL";

export const GETSONG_WAIT = "GETSONG_WAIT";
export const GETSONG_SUCCESS = "GETSONG_SUCCESS";
export const GETSONG_FAIL = "GETSONG_FAIL";